### ISSUE TITLE
Particles not responding between NavBar and Hero text

### ISSUE THREAD

**Issue by akshatcoder-hash** [akshatcoder-hash/FOSS-website-new#17]
# Fixing particles 

## Overview
The particles do not respond to the mouse hover between Navbar and Hero text.

## Description

The particles in this section do not respond to mouse hover.

![image](https://user-images.githubusercontent.com/69577224/188951976-78cfb2bc-07e4-4382-8291-d5de52e5784e.png)

## Expected outcomes

Particles responding and moving with the mouse pointer.

## Skills

HTML, CSS, JavaScript

## Possible mentors

[Akshat Sharma](https://github.com/akshatcoder-hash)

## Expected project size

3 hours.

## Difficulty

Hard

**Comment by Mayank1170** [comment]
> # Use This Proposal Template as a Reference to write your own proposal for Msoc
> # Your Issue Name
> ### Your Background and Technical Skills.
> ### What problem are you trying to solve and Your Approach?
> ### Your Timeline to solve the problem.
> ### Your Commitments.

**Comment by akshatcoder-hash** [comment]
You can start working @Mayank1170!

**Comment by akshatcoder-hash** [comment]
Good work @Mayank1170 #23 solves it!
