### ISSUE TITLE
Redesigning the footer section

### ISSUE THREAD

**Issue by akshatcoder-hash** [akshatcoder-hash/FOSS-website-new#18]
# Blank Footer

## Overview
The footer section of the website is blank and needs to be re-designed..

## Description
Add the social links to the footer with logos and code of conduct.

![image](https://user-images.githubusercontent.com/69577224/188952506-69e0e4cb-d525-4695-ba77-b6e788e71cdc.png)

## Expected outcomes

A footer section containing links to the pages and social media handles.

## Skills

HTML, CSS

## Possible mentors

[Akshat Sharma](https://github.com/akshatcoder-hash)

## Expected project size
2 hours.

## Difficulty

Easy

**Comment by ArunimaShukla03** [comment]
Hey Akshat! I would love to contribute to this.

**Comment by ArunimaShukla03** [comment]
# Blank Footer

## About Me

I'm Arunima Shukla and I have been programming for almost a year and inculcating Open Source for about 4 months now. I have experience in Python, C, C++, HTML, CSS, and JavaScript. My main area of interest is however back-end web development but I am currently wrapping up with the front-end before moving on to the back-end. I am a member of FOSSC and a part of a community promoting women in technical fields (Women In Tech). You may contact me through my LinkedIn [https://www.linkedin.com/in/arunima-shukla-571a42229](https://github.com/akshatcoder-hash/FOSS-website-new/issues/url) or Twitter handle @ArunimaShukla03.

## Issue -

Footer of the website is blank and needs to be redesigned.

## Proposal -

- Adding the social media handles to the footer.
- Adding links to the pages.
- Adding a code of conduct.

## Timeline -

**8th September -  9th September:** Solving and adding the proposed solution for the aforenamed issue.

## Commitments -

- I will try my best to submit the project on time.
- In case of any delay, I will inform the mentor beforehand.
- I will solve the issue with the best of my ability.

**Comment by akshatcoder-hash** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by Mr-Sunglasses** [comment]
@ArunimaShukla03 , you are not committed to your proposal I'm unassigned you in this proposal, please get me back with the new one.

**Comment by adityyaa-10** [comment]
Blank Footer

## About me 
I am Aditya Pandey, I am learning web development for like more than one and a half months. I have had my hands dirty on HTML, CSS and Javascript, till now.
Apart from that, I know C and C++ as well. 

## Issue
Redesigning the footer section.

## Proposal
To add social media icons and add redirecting link to the foss social media handles.

## Timeline
11th September - 12th September

## Commitments
I'll try to submit it as soon as possible.

**Comment by Mr-Sunglasses** [comment]
Thanks @adityyaa-10 for your Proposal, I have assigned you, Looking forward to your PR.

**Comment by Mr-Sunglasses** [comment]
Refer to PR #22

**Comment by Mr-Sunglasses** [comment]
Solved by @adityyaa-10.

**Comment by akshatcoder-hash** [comment]
Good Work @adityyaa-10! Check some [footer examples](https://www.sliderrevolution.com/design/website-footer/) and try to implement more links and information in the footer.
