### ISSUE TITLE
Some elements of the index page are not responsive

### ISSUE THREAD

**Issue by akshatcoder-hash** [akshatcoder-hash/FOSS-website-new#8]
![image](https://user-images.githubusercontent.com/69577224/186722570-150b0f93-05e9-4fe5-9463-7bc38cc804f8.png)

**Comment by akshatcoder-hash** [comment]
![image](https://user-images.githubusercontent.com/69577224/186722514-e55f4512-0505-4a2a-968e-36c226e5ce2f.png)

**Comment by Mayank1170** [comment]
I want to work on it .....
